name: Run CI and tests on Linux

on:
  # Triggers the workflow on push (main branch only) or pull request events
  push:
    branches: [ main ]
  pull_request:

  # Configure workflow manual execution (from the Actions tab)
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: "false"

# Create CI jobs
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [ '8' ]

    env:
      JAVA_OPTS: -Xms2G -Xmx4G -XX:+UseG1GC

    name: Test using Java ${{ matrix.java }}

    # Configure steps of the CI job
    steps:
    
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          
      - name: Clone repo of the libmdbx C library 
        uses: actions/checkout@v3
        with:
          repository: 'erthink/libmdbx'
          fetch-depth: 0 # required to build from tags (https://erthink.github.io/libmdbx/usage.html#autotoc_md33)

      - name: Build libmdbx
        run: make lib
        shell: bash

      - name: Install libmdbx
        run: sudo make install
        shell: bash
        
      - name: Add /usr/local/lib/ to LD_LIBRARY_PATH
        run: echo "LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        shell: bash

      - name: Upload libmdbx.so to workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libmdbx-linux-gnu-x86_64
          path: libmdbx.so
          
      - name: Checks-out the current repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      
      - name: Enable tmate debugging (if the debug_enabled option was set to 'true')
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
      
      - name: Run tests with SBT
        run: |
          echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
          sbt +test
