name: Run CI and tests on Linux

on:
  # Triggers the workflow on push (main branch only) or pull request events
  push:
    branches: [ main ]
  pull_request:

  # Configure workflow manual execution (from the Actions tab)
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: "false"

# Create CI jobs
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [ '8' ]

    env:
      JAVA_OPTS: -Xms2G -Xmx4G -XX:+UseG1GC

    name: Test using Java ${{ matrix.java }}

    # Configure steps of the CI job
    steps:
    
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Checks-out the current repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
          
      - name: Cache LIBMDBX
        id: cache-libmdbx
        uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/libmdbx/
          key: libmdbx-build2

      - name: Clone repo of the libmdbx C library
        if: steps.cache-libmdbx.outputs.cache-hit != 'true'
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'erthink'
          repository: 'libmdbx'

      - name: Build libmdbx
        if: steps.cache-libmdbx.outputs.cache-hit != 'true'
        working-directory: ./libmdbx
        run: |
          ls -al $GITHUB_WORKSPACE/libmdbx/
          make lib
        shell: bash

      - name: Install libmdbx
        working-directory: ./libmdbx
        run: |
          ls -al ./libmdbx
          ls -al $GITHUB_WORKSPACE/libmdbx/
          sudo make install
        shell: bash

      - name: Add /usr/local/lib/ to LD_LIBRARY_PATH
        run: echo "LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        shell: bash

      - name: Upload libmdbx.a and libmdbx.so to workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libmdbx-linux-gnu-x86_64
          path: |
            ./libmdbx/libmdbx.a
            ./libmdbx/libmdbx.so

      - name: Enable tmate debugging (if the debug_enabled option was set to 'true')
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}

      #- name: Run tests with SBT
      #  run: |
      #    echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
      #    sbt +test
