# This is a basic workflow to help you get started with Actions

name: Run tests on Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    #branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    strategy:
      matrix:
        java: [ '8' ]
        
    env:
      JAVA_OPTS: -Xms2G -Xmx4G -XX:+UseG1GC
      
    name: Test using Java ${{ matrix.java }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Restore from cache the previously built ports. If a "cache miss" occurs, then vcpkg is bootstrapped.
      #- name: run-vcpkg
      #  # You may pin to the exact commit or the version.
      #  # uses: lukka/run-vcpkg@c5ce6a7de6e5ce834a25f7d55b6c250a275a6732
      #  uses: lukka/run-vcpkg@v10.1
      
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          
      # Install LLVM in case if cache is missing
      - name: Install LLVM
        shell: pwsh
        run: choco install llvm --version=12.0.0 --allow-downgrade

      - name: Add LLVM on Path
        shell: pwsh
        run: echo "${env:ProgramFiles}\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Assert clang installed and on path
        shell: pwsh
        run: clang --version

      - name: Install libs
        shell: pwsh
        run: vcpkg install zlib --triplet=x64-windows-static
        
      - name: Run tests with SBT
        run: sbt +test
