name: Run tests on Windows

on:
  # Triggers the workflow on push (main branch only) or pull request events
  push:
    branches: [ main ]
  pull_request:

  # Configure workflow manual execution (from the Actions tab)
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: "false"

# Create CI jobs
jobs:
  build:
    runs-on: windows-2019
    
    strategy:
      matrix:
        java: [ '8' ]
        
    env:
      JAVA_OPTS: -Xms2G -Xmx4G -XX:+UseG1GC
      
    name: Test using Java ${{ matrix.java }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      # Install LLVM in case if cache is missing
      #- name: Install LLVM
      #  shell: pwsh
      #  run: choco install llvm --version=12.0.0 --allow-downgrade

      #- name: Add LLVM on Path
      #  shell: pwsh
      #  run: echo "${env:ProgramFiles}\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      #- name: Assert clang installed and on path
      #  shell: pwsh
      #  run: clang --version
        
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: C:/Program Files/LLVM
          key: llvm-12.0.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Install zlib
        shell: pwsh
        run: vcpkg install zlib --triplet=x64-windows-static

      - name: Checks-out the current repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      
      - name: Enable tmate debugging (if the debug_enabled option was set to 'true')
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
        
      - name: Run tests with SBT
        run: sbt +test
